### ISSUE TITLE
Cassette.Nancy does not work with Cassette, Version=2.2.1.13705

### ISSUE THREAD

**Issue by gyurisc** [ChrisMH/Cassette.Nancy#15]
I added the Cassette.Nancy to my nancy project and I am receiving the following error: 

Could not load type 'Cassette.Trace' from assembly 'Cassette, Version=2.2.1.13705, Culture=neutral, PublicKeyToken=null'

[TypeLoadException: Could not load type 'Cassette.Trace' from assembly 'Cassette, Version=2.2.1.13705, Culture=neutral, PublicKeyToken=null'.]
   Cassette.Nancy.BundlesHelper.Cassette.IStartUpTask.Start() in D:\DevP\Cassette.Nancy\src\Cassette.Nancy\BundlesHelper.cs:48
   Cassette.HostBase.RunStartUpTasks() +248
   Cassette.HostBase.Initialize() +253
   Cassette.Aspnet.CassetteHttpModule.InitWithoutTraceLogging() +77
   Cassette.Aspnet.CassetteHttpModule.InitWithTraceLogging() +106
   Cassette.Aspnet.CassetteHttpModule.Init(HttpApplication httpApplication) +131
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +418
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +336
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Could not load type 'Cassette.Trace' from assembly 'Cassette, Version=2.2.1.13705, Culture=neutral, PublicKeyToken=null'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9874568
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +254.

**Comment by GiscardBiamby** [comment]
This can be closed. Cassette.Nancy now works with Cassette 2.3.0.
