### ISSUE TITLE
Does not appear to be working in release mode!

### ISSUE THREAD

**Issue by andycwk** [ChrisMH/Cassette.Nancy#20]
Hi, 
Installed latest version of Cassette.Nancy and in my debug build config everything works fine.  Soon as I switch to Release mode.. my app blows up with the following exception..

[ArgumentNullException: Value cannot be null.
Parameter name: key]
   System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) +6067418
   Nancy.ViewEngines.DefaultViewCache.GetOrAdd(ViewLocationResult viewLocationResult, Func`2 valueFactory) +329
   Nancy.ViewEngines.Razor.RazorViewEngine.GetOrCompileView(ViewLocationResult viewLocationResult, IRenderContext renderContext, Assembly referencingAssembly, Type passedModelType) +186
   System.Dynamic.UpdateDelegates.UpdateAndExecute5(CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) +1170
   CallSite.Target(Closure , CallSite , RazorViewEngine , ViewLocationResult , IRenderContext , Assembly , Object ) +479
   Nancy.ViewEngines.Razor.RazorViewEngine.GetViewInstance(ViewLocationResult viewLocationResult, IRenderContext renderContext, Assembly referencingAssembly, Object model) +1128
   System.Dynamic.UpdateDelegates.UpdateAndExecute5(CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4) +1170
   Nancy.ViewEngines.Razor.<>c__DisplayClass24.<RenderView>b__23(Stream stream) +3804
   Cassette.Nancy.<>c__DisplayClass1.<RewriteResponseContents>b__0(Stream stream) in D:\DevP\Cassette.Nancy\src\Cassette.Nancy\WebHost.cs:98
   Nancy.Hosting.Aspnet.NancyHandler.EndProcessRequest(Task`1 task) +255
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +282
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +630
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

My technology stack is - 
Nancy 0.21, Cassette 2.3.0, nancy.viewengines.razor 0.21, Cassette.Nancy 2.1.0,

Help!!

**Comment by GiscardBiamby** [comment]
Are you using embedded views anywhere? I had this exact same problem, got the same error message when i ran my app in release mode. Turned out it was a problem with the way some of my stuff was being registered. I fixed it by moving some code from IApplicationStartup to IApplicationRegistrations. 

Are you sure this is caused by Cassette.Nancy? Could you try disabling cassette.Nancy and see if you can repro the same thing? Try also disabling Cassette Optimization in your bootstrapper or app startup.

**Comment by andycwk** [comment]
Hi,

Yeh... I should learn to not jump to conclusions so easily :(

After spending more time to pin down the issue..  it turns out that it's a fault within the Nancy.Viewengines.Razor code base :(

https://github.com/NancyFx/Nancy/issues/1281

Sorry for wasting everyone's time!
