### ISSUE TITLE
update to latest nancy 0.12

### ISSUE THREAD

**Issue by prabirshrestha** [ChrisMH/Cassette.Nancy#9]

**Comment by jchannon** [comment]
The issue is that this project uses IStartUp which has now been split into IApplicationStartup and IApplicationRegistrations for Nancy 0.12

**Comment by thefringeninja** [comment]
You can check my nancy-0.12 branch for this. more tests are failing though because the razor view is missing the assembly ref to cassette.nancy. I explicitly set the assembly references in config so I have no idea what is wrong.

**Comment by jchannon** [comment]
I would but you haven't pushed it :)

**Comment by thefringeninja** [comment]
https://github.com/thefringeninja/Cassette.Nancy/tree/nancy-0.12 Did too!
